### ISSUE TITLE
Screenshot capability?

### ISSUE THREAD

**Issue by brycefisher** [fluffysquirrels/webdriver_client_rust#22]
Apologies if I missed this in the documentation, but is it possible to take screenshots from the DriverSession? This is one of my favorite features from the python webdriver client. Thanks!!

**Comment by fluffysquirrels** [comment]
Sorry for the delayed reply!

This is not available yet. I agree the feature is fantastic. Pull requests welcome; are you interested in contributing? :)

If you want to give it a go, the underlying command in the WebDriver REST API spec seems pretty simple ([ref](https://www.w3.org/TR/webdriver/#take-screenshot)): just POST to the write URL and get a Base64-encoded image back.

I'd expect the DriverSession method to return a Screenshot struct, which has a .bytes() method. This would enable future changes to the API.

**Comment by brycefisher** [comment]
Cool! I'm thinking about a different approach now, but this sounds like it might be straightforward to contribute.

**Comment by fluffysquirrels** [comment]
I finally added this to master in efbb0374249608830ef39d4b2412700f63ec4de5, so it should be in the next release (v0.2.4).
